{% set name = "AnaCal" %}
{% set version = "0.5.1" %}
{% set sha256 = "50f6ddb1812248577f02579ec2699a6dce64cb4524fd194f18e178657b0c61f2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mr-superonion/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}


build:
  number: 1
  skip: true  # [py<310 or win]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools >=38
    - fftw >=3.3
    - pybind11 >=2.2
    - pip
  run:
    - python
    - fitsio
    - galsim
    - numpy
    - pydantic
    - matplotlib

test:
  imports:
    - anacal

about:
  home: https://github.com/mr-superonion/AnaCal
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: "Analytical Shear Calibration"
  description: |
    AnaCal is a open-source software to derive linear shear response of
    observables measured from a 2D image.

extra:
  recipe-maintainers:
    - mr-superonion
